spring:
  application:
    name: Product
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
#  spring:
#    security:
#      user:
#        username: user
#        password: user




